// Code generated by generator, DO NOT EDIT.
//
// This file provides the wrappers for exported methods of a global var `globalSignal`.
package signal

var globalSignal Signal
var globalSignalSet bool

func SetGlobalSignal(v Signal) {
	globalSignal = v
	globalSignalSet = true
}

// Beep calls `globalSignal.Beep`.
func Beep() {
	if !globalSignalSet {
		panic("globalSignal must be set before calling Beep()")
	}

	globalSignal.Beep()
}
