// Code generated by generator, DO NOT EDIT.
//
// This file provides the wrappers for exported methods of a global var `globalHouse`.
package test

// Import missing dependencies
import (
	"github.com/mrexox/gen-singleton-functions/example/dog"
	"github.com/mrexox/gen-singleton-functions/example/signal"
)

var globalHouse *House

func SetGlobalHouse(v *House) {
	globalHouse = v
}

// Dog calls `globalHouse.Dog`.
func Dog() *dog.Dog {
	if globalHouse == nil {
		panic("globalHouse must be set before calling Dog()")
	}

	return globalHouse.Dog()
}

// EnableSignals calls `globalHouse.EnableSignals`.
func EnableSignals(signals []signal.Signal) {
	if globalHouse == nil {
		panic("globalHouse must be set before calling EnableSignals()")
	}

	globalHouse.EnableSignals(signals)
}

// Protect calls `globalHouse.Protect`.
func Protect(dog *dog.Dog) error {
	if globalHouse == nil {
		panic("globalHouse must be set before calling Protect()")
	}

	return globalHouse.Protect(dog)
}

// Protected calls `globalHouse.Protected`.
func Protected() (bool, error) {
	if globalHouse == nil {
		panic("globalHouse must be set before calling Protected()")
	}

	return globalHouse.Protected()
}
