// Code generated by generator, DO NOT EDIT.
//
// This file provides the wrappers for exported methods of a global var `globalDog`.
package dog

var globalDog *Dog

func SetGlobalDog(v *Dog) {
	globalDog = v
}

// Bark calls `globalDog.Bark`.
func Bark() error {
	if globalDog == nil {
		panic("globalDog must be set before calling Bark()")
	}

	return globalDog.Bark()
}
